# Generated by Django 4.2.3 on 2023-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_cart_alter_room_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
